export type EmotionVector = { joy:number; calm:number; energy:number; tension:number; nostalgia:number; wonder:number; loneliness:number; chaos:number };
export type Planet = { name:string; radius:number; orbit:number; color:string; archetype:string; lore:string; phase:number };
export type Universe = { name:string; galaxyTitle:string; interpretation:string; message:string; planets:Planet[]; stars:number; palette:string[]; vector:EmotionVector };
const v=(joy:number, calm:number, energy:number, tension:number, nostalgia:number, wonder:number, loneliness:number, chaos:number):EmotionVector=>({joy,calm,energy,tension,nostalgia,wonder,loneliness,chaos});
export const PRESETS:Record<string,{vector:EmotionVector}>={Calm:{vector:v(.45,.92,.25,.1,.3,.72,.22,.08)},Joyful:{vector:v(.96,.42,.82,.12,.15,.65,.08,.22)},Anxious:{vector:v(.12,.08,.8,.92,.12,.35,.38,.52)},Chaotic:{vector:v(.48,.05,.96,.6,.1,.8,.2,.98)},Nostalgic:{vector:v(.38,.65,.28,.24,.95,.48,.32,.16)},Lonely:{vector:v(.08,.55,.15,.3,.62,.38,.95,.08)},Curious:{vector:v(.58,.48,.62,.25,.25,.98,.15,.4)},Euphoric:{vector:v(1,.55,1,.12,.15,.92,.04,.48)},Melancholic:{vector:v(.12,.48,.18,.38,.76,.42,.72,.15)},Custom:{vector:v(.5,.5,.5,.5,.5,.5,.5,.5)}};
const hash=(s:string)=>{let h=2166136261; for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619); return h>>>0}; const rng=(s:string)=>{let a=hash(s);return()=>{a=(Math.imul(1664525,a)+1013904223)>>>0;return a/4294967296}};
const pick=<T,>(r:()=>number,a:T[])=>a[Math.floor(r()*a.length)];
export function analyzeText(text:string):EmotionVector { const t=text.toLowerCase(); const score=(words:string[])=>words.reduce((n,w)=>n+(t.includes(w)?1:0),0); const h=hash(t); const base=(n:number)=>Math.min(1,.18+n*.22+((h>>>n)%25)/100); return v(base(score(["joy","happy","love","bright","grateful"])),base(score(["calm","quiet","peace","soft","still"])),base(score(["energy","excited","alive","go","fire"])),base(score(["anxious","afraid","stress","panic","worried"])),base(score(["remember","miss","old","past","home"])),base(score(["wonder","curious","why","dream","what if"])),base(score(["alone","lonely","empty","isolated"])),base(score(["chaos","wild","mess","angry","! "]))); }
export function generateUniverse(seed:string, e:EmotionVector, preset:string):Universe { const r=rng(seed+JSON.stringify(e)); const palettes=e.joy+e.energy>.95?["#ffab5d","#ff4d87","#ffe095"]:e.calm+e.nostalgia>.9?["#88b9ff","#9b79d0","#f0b48c"]:e.tension+e.chaos>.9?["#ff5370","#9d3cff","#ffa15f"]:["#8aa6ff","#4de0c1","#d98aff"]; const a=["Archive","Hush","Tide","Velvet","Liminal","Halo","Ember","Aster"]; const b=["of Morrow","Drift","Garden","Parallax","Nocturne","Field","Memory","Spiral"]; const planetNames=["Serein","Orris","Vanta","Liora","Calyx","Eidolon","Mira","Nym","Aurel"]; const archetypes=["echo planet","sleeping relay","glass moon","weather archive","unmapped sanctuary"]; const count=e.loneliness>.7?3:5+Math.floor(r()*3); const planets=Array.from({length:count},(_,i)=>({name:`${pick(r,planetNames)}-${Math.floor(10+r()*89)}`,radius:.32+r()*.55,orbit:2.3+i*1.25+r()*.7,color:pick(r,palettes),archetype:pick(r,archetypes),phase:r()*Math.PI*2,lore:pick(r,["It keeps a small light for every return.","Its atmosphere remembers the shape of your voice.","A quiet signal circles its dusk without explanation.","The horizon opens only when you stop looking for it."])})); return {name:`${pick(r,a)} ${pick(r,b)}`,galaxyTitle:`THE ${preset.toUpperCase()} CONSTELLATION`,interpretation:`A ${preset.toLowerCase()} universe of ${e.wonder>.65?"unanswered signals":"slowly shifting light"}.`,message:pick(r,["The universe is listening in its own patient way.","Some distances are invitations, not absences.","A new orbit is possible from here."]),planets,stars:Math.round(400+e.energy*600-e.loneliness*180),palette:palettes,vector:e}; }
export const encodeUniverse=(x:{seed:string;emotion:EmotionVector;preset:string})=>btoa(unescape(encodeURIComponent(JSON.stringify(x)))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
export const decodeUniverse=(x:string|null)=>{try{return x?JSON.parse(decodeURIComponent(escape(atob(x.replaceAll("-","+").replaceAll("_","/")+"==")))):null}catch{return null}};
