"use client";
/* eslint-disable react/no-unescaped-entities */
import { useMemo,useState } from "react";
import type { EmotionVector } from "../generation/universe";
import { audioGarden } from "../audio/AudioGarden";
type Star={id:number;x:number;y:number;name:string};type Shape={name:string;points:[number,number][];lines:[number,number][]};
const shapes:Shape[]=[{name:"The Swan",points:[[20,20],[45,32],[64,22],[56,48],[68,74],[42,65]],lines:[[0,1],[1,2],[1,3],[3,4],[3,5]]},{name:"The Little Fox",points:[[25,67],[37,30],[54,46],[76,28],[66,66],[45,76]],lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]]},{name:"The Lantern",points:[[32,28],[64,28],[76,54],[50,78],[24,54]],lines:[[0,1],[1,2],[2,3],[3,4],[4,0]]}];
const make=(seed:string,n:number)=>Array.from({length:n},(_,i)=>{const h=[...seed].reduce((a,c)=>a+c.charCodeAt(0)*(i+1),i*91);return{id:i,x:8+h%84,y:10+(h*31)%76,name:["Aster","Vela","Mira","Nox","Lumen","Iris"][i%6]}});
export function StarLoom({seed,emotion,sound}:{seed:string;emotion:EmotionVector;sound:boolean}){const [round,setRound]=useState(0),target=shapes[round%shapes.length],initial=useMemo(()=>make(seed,Math.round(13+emotion.wonder*8)),[seed,emotion]);const [stars,setStars]=useState<Star[]>(initial),[lines,setLines]=useState<[number,number][]>([]),[name,setName]=useState("Untitled constellation");const drag=(id:number,e:React.PointerEvent<SVGCircleElement>)=>{const svg=e.currentTarget.ownerSVGElement!;let placed=stars;const move=(m:PointerEvent)=>{const r=svg.getBoundingClientRect();setStars(v=>{placed=v.map(s=>s.id===id?{...s,x:Math.max(3,Math.min(97,(m.clientX-r.left)/r.width*100)),y:Math.max(4,Math.min(96,(m.clientY-r.top)/r.height*100))}:s);return placed})},up=()=>{removeEventListener("pointermove",move);const a=placed.find(s=>s.id===id),b=a&&placed.find(s=>s.id!==id&&Math.hypot(s.x-a.x,s.y-a.y)<15);if(a&&b&&!lines.some(l=>l.includes(id)&&l.includes(b.id))){setLines(v=>[...v,[id,b.id]]);if(sound)audioGarden.note(id,emotion)}};addEventListener("pointermove",move);addEventListener("pointerup",up,{once:true})};return <section className="game loom"><div className="loom-copy"><p className="game-kicker">STAR LOOM · CONSTELLATION SKETCH</p><h2>Draw what<br/>the sky suggests.</h2><p>Use the small reference image as inspiration. There is no penalty—just trace the feeling of its shape.</p><div className="target-card"><span>TONIGHT'S REFERENCE</span><svg viewBox="0 0 100 100">{target.lines.map(([a,b],i)=><line key={i} x1={target.points[a][0]} y1={target.points[a][1]} x2={target.points[b][0]} y2={target.points[b][1]}/>)}{target.points.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="3"/>)}</svg><strong>{target.name}</strong><button onClick={()=>setRound(v=>v+1)}>New reference</button></div></div><svg viewBox="0 0 100 100" className="loom-canvas" aria-label="Drag stars together to recreate the constellation reference">{lines.map(([a,b],i)=>{const x=stars.find(s=>s.id===a)!,y=stars.find(s=>s.id===b)!;return <line key={i} x1={x.x} y1={x.y} x2={y.x} y2={y.y}/>})}{stars.map(s=><g key={s.id}><circle cx={s.x} cy={s.y} r="2.3" onPointerDown={e=>drag(s.id,e)}/><text x={s.x+3} y={s.y-3}>{s.name}</text></g>)}</svg><div className="loom-tools"><input value={name} onChange={e=>setName(e.target.value)} aria-label="Constellation name"/><button onClick={()=>setLines(v=>v.slice(0,-1))}>Undo</button><button onClick={()=>setLines([])}>Clear</button><button onClick={()=>localStorage.setItem("mood-loom",JSON.stringify({name,stars,lines,seed,target:target.name}))}>Save locally</button><span>{lines.length} connections</span></div></section>}
